
POST http://localhost:3000/auth/registerAcc
Content-Type: application/json

{
    "email": "John@gmail.com",
    "password": "123456"
}

###
POST http://localhost:3000/auth/loginAcc
Content-Type: application/json

{
    "email": "trainer2@gmail.com",
    "password": "123456"
}

###
POST http://localhost:3000/auth/logoutAccount

###
POST http://localhost:3000/auth/forgotPassword
Content-Type: application/json

{
    "email": "John@gmail.com"
}

###
POST http://localhost:3000/auth/fitnessLevel/B7UM1BDP8FSkyISZ8xfjSOTHTUu2
Content-Type: application/json

{
   "fitnessLevel":"Beginner"
}

###
POST http://localhost:3000/auth/fitnessGoal/B7UM1BDP8FSkyISZ8xfjSOTHTUu2
Content-Type: application/json

{
   "fitnessGoal":"Reduce stress"
}


###
POST http://localhost:3000/auth/favClass/B7UM1BDP8FSkyISZ8xfjSOTHTUu2
Content-Type: application/json

{
   "favClass":["HIIT","Cardio","Dance"]
}

###
POST http://localhost:3000/auth/completeProfile/B7UM1BDP8FSkyISZ8xfjSOTHTUu2
Content-Type: application/json

{
    "age": 22,
    "gender" : "Male",
    "height": 180,
    "name": "John Tan",
    "role": "Student",
    "username":"John",
    "weight": 60
}


###
GET http://localhost:3000/goals/getAllUserGoals/B7UM1BDP8FSkyISZ8xfjSOTHTUu2


###
POST http://localhost:3000/goals/addGoal
Content-Type: application/json

{
    "uid": "B7UM1BDP8FSkyISZ8xfjSOTHTUu2",
    "title": "running",
    "status": false
}

###
DELETE  http://localhost:3000/goals/deleteGoal/D1AGvqd5XVKskEJjXlCR

###
PATCH http://localhost:3000/goals/updateGoal/D1AGvqd5XVKskEJjXlCR
Content-Type: application/json

{
    "uid": "B7UM1BDP8FSkyISZ8xfjSOTHTUu2",
    "title": "jogging",
    "status": false
}

###
GET http://localhost:3000/auth/getUserById/B7UM1BDP8FSkyISZ8xfjSOTHTUu2

###
PATCH http://localhost:3000/profile/updateProfile/B7UM1BDP8FSkyISZ8xfjSOTHTUu2
Content-Type: application/json

{
    "username":"Johnny",
    "age": 24,
    "weight": 70,
    "height": 160
}

###
DELETE http://localhost:3000/auth/deleteAccount/Lb8r8mfoq6NHWDy40fKnuGuByQZ2


###
GET http://localhost:3000/tips/getAllUserTips/iOVD6KGFyqajDpo2tDZ1FVPqy302


###
POST http://localhost:3000/tips/addTip
Content-Type: application/json

{
    "uid": "iOVD6KGFyqajDpo2tDZ1FVPqy302",
    "title": "running",
    "desc": "How to run effectively"
}

###
DELETE  http://localhost:3000/tips/deleteTip/D2rmP5I7vnuI4BeCK93i

###
PATCH http://localhost:3000/tips/updateTip/D2rmP5I7vnuI4BeCK93i
Content-Type: application/json

{
    "uid": "iOVD6KGFyqajDpo2tDZ1FVPqy302",
    "title": "jogging",
    "desc": "When is the best time to jog."
}

